import type { Metadata } from "next";
import { Reddit_Sans } from "next/font/google";
import "./globals.css";
import { ChildrenProps } from "@/types/components";

const redditSans = Reddit_Sans({
  subsets: ["latin"],
  variable: "--font-reddit-sans",
  weight: ["200", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Biblioteca UTMA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<ChildrenProps>) {
  return (
    <html lang="en">
      <body className={`${redditSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
